#!/usr/bin/env bash
# Run Medja against a fully local Supabase stack (Postgres + Auth + Storage).
# Requires Docker (Docker Desktop or Colima) running on your machine.
#
#   ./scripts/dev-local.sh        # starts local Supabase, wires env, then `npm run dev`
#
set -euo pipefail
cd "$(dirname "$0")/.."

if ! docker info >/dev/null 2>&1; then
  echo "✗ Docker is not running. Start Docker Desktop (or 'colima start') and retry."
  exit 1
fi

echo "▸ Starting local Supabase (applies all migrations in supabase/migrations/)…"
supabase start

echo "▸ Writing local keys into .env.local…"
eval "$(supabase status -o env)"   # exports API_URL, ANON_KEY, SERVICE_ROLE_KEY
cat > .env.local <<EOF
# Local Supabase stack (generated by scripts/dev-local.sh)
NEXT_PUBLIC_SUPABASE_URL=${API_URL}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${ANON_KEY}
SUPABASE_SERVICE_ROLE_KEY=${SERVICE_ROLE_KEY}
NEXT_PUBLIC_APP_URL=http://localhost:3000
# Paystack (optional locally)
PAYSTACK_SECRET_KEY=
NEXT_PUBLIC_PAYSTACK_PUBLIC_KEY=
EOF

echo ""
echo "✓ Local Supabase is up. Studio:  http://localhost:54323"
echo "  Magic-link emails land in Inbucket:  http://localhost:54324"
echo ""
echo "▸ Starting the app on http://localhost:3000 …"
npm run dev
